[package]
name = "app_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_derive = { workspace = true }

# Configuration management
config = "0.13.1"