//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
    pub deleted_at: DateTime,
    pub updated_at: DateTime,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bill_parse_requests::Entity")]
    BillParseRequests,
}

impl Related<super::bill_parse_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillParseRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
